export { default as Homescreen } from './homescreen/Homescreen';
// export { default as Pricing } from './pricing/Pricing';
export { default as Support } from './support/support';
export { default as Validate } from './validate/Validate';
export { default as Checkout } from './checkout/Checkout';
export { default as TermsOfService } from "./termsOfService/TermsOfService";
export { default as PrivacyPolicy } from './privacyPolicy/PrivaciPolicy'; 
export { default as PageNotFound } from './pageNotFound/PageNotFound';
export { default as Success } from './success/Success';
export { default as ContactSuccess} from './success/ContactSuccess';
export { default as Failed } from './failed/Failed';
export { default as ContactUs} from './contactUs/ContactUs';
export { default as HowItWorks } from './howItWorks/HowItWorks';
export { default as Faq } from './faq/Faq';
export { default as Docs } from './docs/Docs';
export { default as ComparePlans } from './comparePlans/ComparePlans';
export { default as ContactEnterprise } from './contactEnterprise/ContactEnterprise';
export { default as SupportPlans } from './supportPlans/SupportPlans';
export { default as Trial } from './trial/Trial';
export { default as FreePlan } from './freePlan/FreePlan';
export { default as Plugins } from './plugins/Plugins'
export { default as PluginPage } from './pluginPage/PluginPage';
export * from './governance/Governance';