export { default as Homescreen } from './homescreen/Homescreen';
export { default as Pricing } from './pricing/Pricing';
export { default as Support } from './support/support';
export { default as Validate } from './validate/Validate';
export { default as Checkout } from './checkout/Checkout';
export { default as TermsOfService } from "./termsOfService/TermsOfService";
export { default as PrivacyPolicy } from './privacyPolicy/PrivaciPolicy'; 
export { default as PageNotFound } from './pageNotFound/PageNotFound';
export { default as Success } from './success/Success';
export { default as Failed } from './failed/Failed';
export { default as ContactUs} from './contactUs/ContactUs';
export { default as HowItWorks } from './howItWorks/HowItWorks';
