import style from "./_SupportBenefits.module.scss";
import { FaLayerGroup, FaInfoCircle, FaUsers, FaMedal, FaWrench } from "react-icons/fa";

const SupportBenefits = () => {
  return (
    <div className={style.cards}>
      <h2 className={style.title}>What&apos;s included in our support</h2>
      {/* Card 01 */}
      <div className={style.card}>
        <div className={style.card__icon}>
        <FaInfoCircle />
        </div>
        <div className={style.card__details}>
          <h2 className={style["card__details-title"]}>Questions</h2>
          <p className={style["card__details-desc"]}>
            Obtain answers about installation, configuration, and use of our
            products while considering the details of your workflow, as well as
            support for any and all artifacts generated by the product.
          </p>
        </div>
      </div>
      {/* Card 02 */}
      <div className={style.card}>
        <div className={style.card__icon}>
          <FaLayerGroup />
        </div>
        <div className={style.card__details}>
          <h2 className={style["card__details-title"]}>Troubleshooting</h2>
          <p className={style["card__details-desc"]}>
            Any issues that may pop up will be quickly solved and back to normal
            working order.
          </p>
        </div>
      </div>
      {/* Card 03 */}
      <div className={style.card}>
        <div className={style.card__icon}>
        <FaWrench />
        </div>
        <div className={style.card__details}>
          <h2 className={style["card__details-title"]}>Bug fixes</h2>
          <p className={style["card__details-desc"]}>
            Report any bugs you find and help us understand how they impact you
            to get them fixed, and find ways to avoid it in the future.
          </p>
        </div>
      </div>
      {/* Card 04 */}
      <div className={style.card}>
        <div className={style.card__icon}>
          <FaUsers />
        </div>
        <div className={style.card__details}>
          <h2 className={style["card__details-title"]}>
            Interact with our team
          </h2>
          <p className={style["card__details-desc"]}>
            All our subscribers havesubscribers users have access to our
            <strong>Service Portal</strong> where they can send and follow the process of fulfilling all their
            requests.
          </p>
        </div>
      </div>
      {/* Card 05 */}
      <div className={style.card}>
        <div className={style.card__icon}>
          <FaMedal />
        </div>
        <div className={style.card__details}>
          <h2 className={style["card__details-title"]}>
            Guaranteed response times
          </h2>
          <p className={style["card__details-desc"]}>
            We ensure that we will respond to your requests according to the
            type of support contracted.
            <br />- In <strong>Support Standard</strong> we respond within 5
            working days.
            <br />- In <strong>Support Premium</strong> within 3 working days.
            <br />
            <strong>
              It is important to note that the support service is not an
              emergency service. 
            </strong> <br/>
             In some special cases, support service 
            will not be available. These
            days will be informed by email at least 3 weeks in advance.
          </p>
        </div>
      </div>
    </div>
  );
};

export default SupportBenefits;
