name: Upload to S3 Homolog

on:
  push:
    branches: [ homolog ]
  pull_request:
    branches: [ homolog ]

permissions:
  id-token: write
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      
      - name: Build Project
        run: | 
           yarn version
           yarn
           cat > '.env.local' <<EOT
           NEXT_PUBLIC_ANALYTICS_ID=${{ secrets.ANALYTICS_ID }}
           NEXT_PUBLIC_LAMBDA_BASE_URL=${{ secrets.LAMBDA_BASE_URL_HOMOLOG }}
           NEXT_PUBLIC_LAMBDA_API_KEY=${{ secrets.LAMBDA_API_KEY_HOMOLOG }}
           NEXT_PUBLIC_PAYPAL_CLIENT_ID=${{ secrets.PAYPAL_CLIENT_ID }}
           NEXT_PUBLIC_PAYPAL_PREMIUM_ANUAL=${{ secrets.PAYPAL_PREMIUM_ANUAL }}
           NEXT_PUBLIC_PAYPAL_PREMIUM_MONTHLY=${{ secrets.PAYPAL_PREMIUM_MONTHLY }}
           NEXT_PUBLIC_PAYPAL_STANDARD_ANUAL=${{ secrets.PAYPAL_STANDARD_ANUAL }}
           NEXT_PUBLIC_PAYPAL_STANDARD_MONTHLY=${{ secrets.PAYPAL_STANDARD_MONTHLY }}

           EOT
           yarn build
           ls -ltrh out

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::559803878497:role/landing_page_actions_role
          aws-region: us-east-1

      - name: Deploy static site to S3 bucket
        run: |
           aws s3 sync out s3://${{ secrets.AWS_BUCKET_HML }} --acl public-read
      - name: Homolog docs URL
        run: |
          echo "http://${{ secrets.AWS_BUCKET_HML }}.s3-website-us-east-1.amazonaws.com/"
