name: Upload to S3

on:
  push:
    branches: [ homolog ]
  pull_request:
    branches: [ homolog ]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      
      - name: Build Project
        run: | 
           yarn version
           yarn
           cat > '.env.local' <<EOT
           NEXT_PUBLIC_ANALYTICS_ID=${{ secrets.ANALYTICS_ID }}
           NEXT_PUBLIC_LAMBDA_BASE_URL=${{ secrets.LAMBDA_BASE_URL }}
           NEXT_PUBLIC_PAYPAL_CLIENT_ID=${{ secrets.PAYPAL_CLIENT_ID }}
           NEXT_PUBLIC_PAYPAL_PREMIUM_ANUAL=${{ secrets.PAYPAL_PREMIUM_ANUAL }}
           NEXT_PUBLIC_PAYPAL_PREMIUM_MONTHLY=${{ secrets.PAYPAL_PREMIUM_MONTHLY }}
           NEXT_PUBLIC_PAYPAL_STANDARD_ANUAL=${{ secrets.PAYPAL_STANDARD_ANUAL }}
           NEXT_PUBLIC_PAYPAL_STANDARD_MONTHLY=${{ secrets.PAYPAL_STANDARD_MONTHLY }}

           EOT
           cat .env.local 
           yarn build
           ls -ltrh out

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy static site to S3 bucket
        run: aws s3 sync out s3://${{ secrets.AWS_BUCKET_HML }} --acl public-read
              
#     - uses: shallwefootball/s3-upload-action@master
#       name: Upload S3
#       id: S3
#       with:
#         aws_key_id: ${{ secrets.AWS_KEY_ID }}
#         aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
#         aws_bucket: ${{ secrets.AWS_BUCKET }}
#         source_dir: 'out'
