name: Upload to S3 Production

on:
  push:
    branches: [ homolog ]

permissions:
  id-token: write
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Getting versions
        run: |
          echo "app_version=$(jq -r '.version' package.json)" >> $GITHUB_ENV
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::844606521248:role/landing_page_actions_role
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: 'veecode-platform/landing-page'
          IMAGE_TAG: ${{ env.app_version }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      # - name: Deploy static site to S3 bucket
      #   run: |
      #     aws s3 rm s3://${{ secrets.AWS_BUCKET }} --recursive
      #     aws s3 sync out s3://${{ secrets.AWS_BUCKET }} --acl public-read
      #     aws cloudfront create-invalidation --distribution-id E10554892ALDF9 --paths "/*"
