name: Export Secrets

on:
  workflow_dispatch:

jobs:
  export-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Load environment variables
        run: |
          cat > '.env' <<EOT
          NEXT_PUBLIC_ANALYTICS_ID=${{ secrets.ANALYTICS_ID }}
          NEXT_PUBLIC_LAMBDA_BASE_URL=${{ secrets.LAMBDA_BASE_URL }}
          NEXT_PUBLIC_LAMBDA_API_KEY=${{ secrets.LAMBDA_API_KEY }}
          NEXT_PUBLIC_GOOGLE_TAG_MANAGER=${{ secrets.GOOGLE_TAG_MANAGER}}
          NEXT_PUBLIC_NEUROLEAD_ID=${{ secrets.NEUROLEAD_ID}}
          NEXT_PUBLIC_HOST_URL="https://${{ env.HOST }}"
          EOT
          sed -i 's/[[:space:]]//g' .env


      - name: Setting up kubectl client
        uses: azure/setup-kubectl@v4

      - name:
        run: |
          kubectl create secret generic landing-page-secret --from-env-file=.env -n vkpr --dry-run=client -o yaml > secrets.yml

         
      - name: Upload secrets artifact
        uses: actions/upload-artifact@v3
        with:
          name: secrets
          path: secrets.yml